eureka:
  client:
    serviceUrl:
#      defaultZone: '@eureka.defaultZone@'
      defaultZone: 'http://localhost:8062/eureka/'
  instance:
    preferIpAddress: true
server:
#  port: @server.port@
  port: 8082
spring:
  application:
    name: service-manager
  http:
    multipart:
      max-file-size: 6000Mb
      max-request-size: 6000Mb

feign:
  okhttp:
    enabled: true
